//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Party.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppLevelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLevelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Party.Application.Resources.AppLevelResource", typeof(AppLevelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///To be able to fetch approprate servers by country or by protocol, you mast pass correct names. To see example countries you can take a look at CountryId and VpnProtocol domain enums values. Or you can referance to NordVPN official API guide.
        ///
        ///To be able to see the action flow,  you can take a look at the logs in [Party.Cli\logs] files..
        /// </summary>
        internal static string ConsoleAppDescription {
            get {
                return ResourceManager.GetString("ConsoleAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartyCLI - VPN Servers.
        /// </summary>
        internal static string ConsoleAppTitle {
            get {
                return ResourceManager.GetString("ConsoleAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dotnet run server_list.
        /// </summary>
        internal static string ListServersExample {
            get {
                return ResourceManager.GetString("ListServersExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dotnet run server_list --local.
        /// </summary>
        internal static string ListServersLocalExample {
            get {
                return ResourceManager.GetString("ListServersLocalExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all available servers in local environment which were fetched from NordVpn API:.
        /// </summary>
        internal static string ListServersLocalTitle {
            get {
                return ResourceManager.GetString("ListServersLocalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dotnet run server_list --{countryName}.
        /// </summary>
        internal static string ListServersOfCountryExample {
            get {
                return ResourceManager.GetString("ListServersOfCountryExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all available servers from NordVpn API (by country name):.
        /// </summary>
        internal static string ListServersOfCountryTitle {
            get {
                return ResourceManager.GetString("ListServersOfCountryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dotnet run server_list --{protocolName}.
        /// </summary>
        internal static string ListServersOfProtocolExample {
            get {
                return ResourceManager.GetString("ListServersOfProtocolExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List specific protocol servers from NordVpn API:.
        /// </summary>
        internal static string ListServersOfProtocolTitle {
            get {
                return ResourceManager.GetString("ListServersOfProtocolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all available servers from NordVpn API:.
        /// </summary>
        internal static string ListServersTitle {
            get {
                return ResourceManager.GetString("ListServersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No servers to display..
        /// </summary>
        internal static string NoServersProvided {
            get {
                return ResourceManager.GetString("NoServersProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0, -40} Load: {1, 3} Status: {2}.
        /// </summary>
        internal static string ServerInfoModel {
            get {
                return ResourceManager.GetString("ServerInfoModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server List:.
        /// </summary>
        internal static string ServerListing {
            get {
                return ResourceManager.GetString("ServerListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total servers: {0}.
        /// </summary>
        internal static string TotalServers {
            get {
                return ResourceManager.GetString("TotalServers", resourceCulture);
            }
        }
    }
}
